/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package cap_presentacion;

import cap_logica.Cliente;
import cap_logica.Strings;
import java.awt.Color;
import java.sql.Date;
import javax.swing.JOptionPane;

/**
 *
 * @author Sh
 */
public class PnlMtnmtRegistrarCliente extends javax.swing.JPanel {
    
    public final String dniEjemplo = "Ejm: 73954768";

    /**
     * Creates new form PnlMtnmtRegistrarCliente
     */
    public PnlMtnmtRegistrarCliente() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        imgCliente = new javax.swing.JLabel();
        txDni = new javax.swing.JLabel();
        tfDni = new javax.swing.JTextField();
        txNombre = new javax.swing.JLabel();
        tfNombre = new javax.swing.JTextField();
        txApPaterno = new javax.swing.JLabel();
        tfApPaterno = new javax.swing.JTextField();
        txApMaterno = new javax.swing.JLabel();
        tfApMaterno = new javax.swing.JTextField();
        txFechaNaci = new javax.swing.JLabel();
        dcFechaNaci = new com.toedter.calendar.JDateChooser();
        txDireccion = new javax.swing.JLabel();
        tfDireccion = new javax.swing.JTextField();
        txTelefono = new javax.swing.JLabel();
        tfTelefono = new javax.swing.JTextField();
        btRegCliente = new javax.swing.JButton();

        setBackground(new java.awt.Color(153, 204, 255));
        setAlignmentY(0.0F);
        setLayout(new java.awt.GridBagLayout());

        imgCliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/imgRegCliente.jpg"))); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridheight = 8;
        add(imgCliente, gridBagConstraints);

        txDni.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        txDni.setText("DNI:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(4, 30, 0, 0);
        add(txDni, gridBagConstraints);

        tfDni.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        tfDni.setForeground(new java.awt.Color(153, 153, 153));
        tfDni.setText(Strings.ejmDni);
        tfDni.setPreferredSize(new java.awt.Dimension(450, 35));
        tfDni.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                tfDniMousePressed(evt);
            }
        });
        tfDni.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tfDniKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tfDniKeyReleased(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(0, 20, 0, 0);
        add(tfDni, gridBagConstraints);

        txNombre.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        txNombre.setText("Nombre:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(20, 30, 0, 0);
        add(txNombre, gridBagConstraints);

        tfNombre.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        tfNombre.setForeground(new java.awt.Color(153, 153, 153));
        tfNombre.setText(Strings.ejmNombre);
        tfNombre.setPreferredSize(new java.awt.Dimension(450, 35));
        tfNombre.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                tfNombreMousePressed(evt);
            }
        });
        tfNombre.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tfNombreKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tfNombreKeyReleased(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(16, 20, 0, 0);
        add(tfNombre, gridBagConstraints);

        txApPaterno.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        txApPaterno.setText("Apellido Paterno:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(20, 30, 0, 0);
        add(txApPaterno, gridBagConstraints);

        tfApPaterno.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        tfApPaterno.setForeground(new java.awt.Color(153, 153, 153));
        tfApPaterno.setText(Strings.ejmApPaterno);
        tfApPaterno.setPreferredSize(new java.awt.Dimension(450, 35));
        tfApPaterno.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                tfApPaternoMousePressed(evt);
            }
        });
        tfApPaterno.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tfApPaternoKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tfApPaternoKeyReleased(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(16, 20, 0, 0);
        add(tfApPaterno, gridBagConstraints);

        txApMaterno.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        txApMaterno.setText("Apellido Materno:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(20, 30, 0, 0);
        add(txApMaterno, gridBagConstraints);

        tfApMaterno.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        tfApMaterno.setForeground(new java.awt.Color(153, 153, 153));
        tfApMaterno.setText(Strings.ejmApMaterno);
        tfApMaterno.setPreferredSize(new java.awt.Dimension(450, 35));
        tfApMaterno.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                tfApMaternoMousePressed(evt);
            }
        });
        tfApMaterno.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tfApMaternoKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tfApMaternoKeyReleased(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(16, 20, 0, 0);
        add(tfApMaterno, gridBagConstraints);

        txFechaNaci.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        txFechaNaci.setText("Fecha de nacimiento:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(20, 30, 0, 0);
        add(txFechaNaci, gridBagConstraints);

        dcFechaNaci.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        dcFechaNaci.setOpaque(false);
        dcFechaNaci.setPreferredSize(new java.awt.Dimension(450, 35));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(16, 20, 0, 0);
        add(dcFechaNaci, gridBagConstraints);

        txDireccion.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        txDireccion.setText("Dirección:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(20, 30, 0, 0);
        add(txDireccion, gridBagConstraints);

        tfDireccion.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        tfDireccion.setForeground(new java.awt.Color(153, 153, 153));
        tfDireccion.setText(Strings.ejmDireccion);
        tfDireccion.setPreferredSize(new java.awt.Dimension(450, 35));
        tfDireccion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                tfDireccionMousePressed(evt);
            }
        });
        tfDireccion.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tfDireccionKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tfDireccionKeyReleased(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(16, 20, 0, 0);
        add(tfDireccion, gridBagConstraints);

        txTelefono.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        txTelefono.setText("Teléfono:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(20, 30, 0, 0);
        add(txTelefono, gridBagConstraints);

        tfTelefono.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        tfTelefono.setForeground(new java.awt.Color(153, 153, 153));
        tfTelefono.setText(Strings.ejmTelefono);
        tfTelefono.setPreferredSize(new java.awt.Dimension(450, 35));
        tfTelefono.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                tfTelefonoMousePressed(evt);
            }
        });
        tfTelefono.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tfTelefonoKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tfTelefonoKeyReleased(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(16, 20, 0, 0);
        add(tfTelefono, gridBagConstraints);

        btRegCliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/addClientex48.png"))); // NOI18N
        btRegCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btRegClienteActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 7;
        gridBagConstraints.gridwidth = 4;
        gridBagConstraints.insets = new java.awt.Insets(30, 0, 0, 0);
        add(btRegCliente, gridBagConstraints);
    }// </editor-fold>//GEN-END:initComponents

    private void btRegClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btRegClienteActionPerformed
        // TODO add your handling code here:
        try{
            Color negro = new Color(0,0,0);
            Color rojo = new Color(255,51,51);
            java.util.Date fechaActual = new java.util.Date();
            
            //comparar el 'año actual' con el 'año de nacimiento' del cliente para comprobar si es mayor de edad
            if(fechaActual.getYear() - dcFechaNaci.getDate().getYear() >= 18 
                    && tfDni.getForeground().equals(negro)  && tfTelefono.getForeground().equals(negro)){
                Cliente objCli = new Cliente();

                objCli.setDni(tfDni.getText());
                objCli.setNombre(tfNombre.getText());
                objCli.setApellidoPaterno(tfApPaterno.getText());
                objCli.setApellidoMaterno(tfApMaterno.getText());
                    //'fecha' de tipo (java.sql.Date) para ingresar a la BD, inicializado con la fecha obtenida del JDateChooser
                    Date fecha = new Date(dcFechaNaci.getDate().getTime());
                objCli.setFechaNacimiento(fecha);
                objCli.setDireccion(tfDireccion.getText());
                objCli.setTelefono(tfTelefono.getText());

                objCli.agregar();

                JOptionPane.showMessageDialog(this,"Cliente REGISTRADO",
                            "MENSAJE DEL SISTEMA", JOptionPane.INFORMATION_MESSAGE); 

                tfDni.setText(Strings.ejmDni);
                tfDni.setCaretPosition(0);
                tfDni.setForeground(new Color(153,153,153));
                
                tfNombre.setText(Strings.ejmNombre);
                tfNombre.setCaretPosition(0);
                tfNombre.setForeground(new Color(153,153,153));
                
                tfApPaterno.setText(Strings.ejmApPaterno);
                tfApPaterno.setCaretPosition(0);
                tfApPaterno.setForeground(new Color(153,153,153));
                
                tfApMaterno.setText(Strings.ejmApMaterno);
                tfApMaterno.setCaretPosition(0);
                tfApMaterno.setForeground(new Color(153,153,153));
                
                dcFechaNaci.setDate(null);
                
                tfDireccion.setText(Strings.ejmDireccion);
                tfDireccion.setCaretPosition(0);
                tfDireccion.setForeground(new Color(153,153,153));
                
                tfTelefono.setText(Strings.ejmTelefono);
                tfTelefono.setCaretPosition(0);
                tfTelefono.setForeground(new Color(153,153,153));
                
                tfDni.requestFocus();
                
            }else if(tfDni.getForeground().equals(rojo)){
                JOptionPane.showMessageDialog(this,"DNI con LETRAS",
                            "ERROR DEL SISTEMA", JOptionPane.ERROR_MESSAGE);
                
            }else if(fechaActual.getYear() - dcFechaNaci.getDate().getYear() < 18){
                JOptionPane.showMessageDialog(this,"Cliente MENOR DE EDAD",
                            "MENSAJE DEL SISTEMA", JOptionPane.INFORMATION_MESSAGE);
                
            }else if(tfTelefono.getForeground().equals(rojo)){
                JOptionPane.showMessageDialog(this,"Telefono con LETRAS",
                            "ERROR DEL SISTEMA", JOptionPane.ERROR_MESSAGE);
            }
            
        }catch(Exception  error){
            JOptionPane.showMessageDialog(this,error.getMessage(),
                        "ERROR DEL SISTEMA", JOptionPane.ERROR_MESSAGE);        
        }
    }//GEN-LAST:event_btRegClienteActionPerformed

    /*
        DETALLES DE TEXT FIELD: 
            inicio del caret;
            color de letras. gris - ejemplo, rojo - incorrecto, negro - correcto;
            text field vacio = texto de ejemplo;
    */
    
    private void tfDniMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tfDniMousePressed
        // TODO add your handling code here:      
        if(tfDni.getText().equals(Strings.ejmDni)){

            tfDni.setCaretPosition(0);
            //tfDni.setCaretColor(new Color(0,0,0));
        }
    }//GEN-LAST:event_tfDniMousePressed

    private void tfDniKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfDniKeyPressed
        // TODO add your handling code here:
        if(tfDni.getText().equals(Strings.ejmDni)){

            tfDni.setForeground(new Color(0,0,0));
            tfDni.setText("");
        }
    }//GEN-LAST:event_tfDniKeyPressed

    private void tfDniKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfDniKeyReleased
        // TODO add your handling code here:
        boolean letra = false;
        
        if(tfDni.getCaretPosition() == 0 && tfDni.getText().equals("")){

            tfDni.setText(Strings.ejmDni);
            tfDni.setForeground(new Color(153,153,153));
            tfDni.setCaretPosition(0);
        }else{

            for (int i = 0; i < tfDni.getText().length(); i++) {
                char c = tfDni.getText().charAt(i);

                if(c != '1' && c != '2' && c != '3' && c != '4' && c != '5'
                    && c != '6' && c != '7' && c != '8' && c != '9' && c != '0'){

                    letra = true;
                }
            }
            
            if(letra == true || tfDni.getText().length() > 8){
                tfDni.setForeground(new Color(255,51,51)); // rojo
            }else{
                tfDni.setForeground(new Color(0,0,0)); // negro
            }
        }
    }//GEN-LAST:event_tfDniKeyReleased

    private void tfNombreMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tfNombreMousePressed
        // TODO add your handling code here:
        if(tfNombre.getText().equals(Strings.ejmNombre)){

            tfNombre.setCaretPosition(0);
        }
    }//GEN-LAST:event_tfNombreMousePressed

    private void tfNombreKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfNombreKeyPressed
        // TODO add your handling code here:
        if(tfNombre.getText().equals(Strings.ejmNombre)){

            tfNombre.setForeground(new Color(0,0,0));
            tfNombre.setText("");
        }
    }//GEN-LAST:event_tfNombreKeyPressed

    private void tfNombreKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfNombreKeyReleased
        // TODO add your handling code here:
        if(tfNombre.getCaretPosition() == 0 && tfNombre.getText().equals("")){

            tfNombre.setText(Strings.ejmNombre);
            tfNombre.setForeground(new Color(153,153,153));
            tfNombre.setCaretPosition(0);
        }
    }//GEN-LAST:event_tfNombreKeyReleased

    private void tfApPaternoMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tfApPaternoMousePressed
        // TODO add your handling code here:
        if(tfApPaterno.getText().equals(Strings.ejmApPaterno)){

            tfApPaterno.setCaretPosition(0);
        }
    }//GEN-LAST:event_tfApPaternoMousePressed

    private void tfApPaternoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfApPaternoKeyPressed
        // TODO add your handling code here:
        if(tfApPaterno.getText().equals(Strings.ejmApPaterno)){

            tfApPaterno.setForeground(new Color(0,0,0));
            tfApPaterno.setText("");
        }
    }//GEN-LAST:event_tfApPaternoKeyPressed

    private void tfApPaternoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfApPaternoKeyReleased
        // TODO add your handling code here:
        if(tfApPaterno.getCaretPosition() == 0 && tfApPaterno.getText().equals("")){

            tfApPaterno.setText(Strings.ejmApPaterno);
            tfApPaterno.setForeground(new Color(153,153,153));
            tfApPaterno.setCaretPosition(0);
        }
    }//GEN-LAST:event_tfApPaternoKeyReleased

    private void tfApMaternoMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tfApMaternoMousePressed
        // TODO add your handling code here:
        if(tfApMaterno.getText().equals(Strings.ejmApMaterno)){

            tfApMaterno.setCaretPosition(0);
        }
    }//GEN-LAST:event_tfApMaternoMousePressed

    private void tfApMaternoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfApMaternoKeyPressed
        // TODO add your handling code here:
        if(tfApMaterno.getText().equals(Strings.ejmApMaterno)){

            tfApMaterno.setForeground(new Color(0,0,0));
            tfApMaterno.setText("");
        }
    }//GEN-LAST:event_tfApMaternoKeyPressed

    private void tfApMaternoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfApMaternoKeyReleased
        // TODO add your handling code here:
        if(tfApMaterno.getCaretPosition() == 0 && tfApMaterno.getText().equals("")){

            tfApMaterno.setText(Strings.ejmApMaterno);
            tfApMaterno.setForeground(new Color(153,153,153));
            tfApMaterno.setCaretPosition(0);
        }
    }//GEN-LAST:event_tfApMaternoKeyReleased

    private void tfDireccionMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tfDireccionMousePressed
        // TODO add your handling code here:
        if(tfDireccion.getText().equals(Strings.ejmDireccion)){

            tfDireccion.setCaretPosition(0);
        }
    }//GEN-LAST:event_tfDireccionMousePressed

    private void tfDireccionKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfDireccionKeyPressed
        // TODO add your handling code here:
        if(tfDireccion.getText().equals(Strings.ejmDireccion)){

            tfDireccion.setForeground(new Color(0,0,0));
            tfDireccion.setText("");
        }
    }//GEN-LAST:event_tfDireccionKeyPressed

    private void tfDireccionKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfDireccionKeyReleased
        // TODO add your handling code here:
        if(tfDireccion.getCaretPosition() == 0 && tfDireccion.getText().equals("")){

            tfDireccion.setText(Strings.ejmDireccion);
            tfDireccion.setForeground(new Color(153,153,153));
            tfDireccion.setCaretPosition(0);
        }
    }//GEN-LAST:event_tfDireccionKeyReleased

    private void tfTelefonoMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tfTelefonoMousePressed
        // TODO add your handling code here:
        if(tfTelefono.getText().equals(Strings.ejmTelefono)){

            tfTelefono.setCaretPosition(0);
        }
    }//GEN-LAST:event_tfTelefonoMousePressed

    private void tfTelefonoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfTelefonoKeyPressed
        // TODO add your handling code here:
        if(tfTelefono.getText().equals(Strings.ejmTelefono)){

            tfTelefono.setForeground(new Color(0,0,0));
            tfTelefono.setText("");
        }
    }//GEN-LAST:event_tfTelefonoKeyPressed

    private void tfTelefonoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfTelefonoKeyReleased
        // TODO add your handling code here:
        boolean letra = false;
        
        if(tfTelefono.getCaretPosition() == 0 && tfTelefono.getText().equals("")){

            tfTelefono.setText(Strings.ejmTelefono);
            tfTelefono.setForeground(new Color(153,153,153));
            tfTelefono.setCaretPosition(0);
        }else{

            for (int i = 0; i < tfTelefono.getText().length(); i++) {
                char c = tfTelefono.getText().charAt(i);

                if(c != '1' && c != '2' && c != '3' && c != '4' && c != '5'
                    && c != '6' && c != '7' && c != '8' && c != '9' && c != '0'){

                    letra = true;
                }
            }
            
            if(letra == true || tfTelefono.getText().length() > 9){
                tfTelefono.setForeground(new Color(255,51,51)); // rojo
            }else{
                tfTelefono.setForeground(new Color(0,0,0)); // negro
            }
        }
    }//GEN-LAST:event_tfTelefonoKeyReleased


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btRegCliente;
    private com.toedter.calendar.JDateChooser dcFechaNaci;
    private javax.swing.JLabel imgCliente;
    private javax.swing.JTextField tfApMaterno;
    private javax.swing.JTextField tfApPaterno;
    private javax.swing.JTextField tfDireccion;
    private javax.swing.JTextField tfDni;
    private javax.swing.JTextField tfNombre;
    private javax.swing.JTextField tfTelefono;
    private javax.swing.JLabel txApMaterno;
    private javax.swing.JLabel txApPaterno;
    private javax.swing.JLabel txDireccion;
    private javax.swing.JLabel txDni;
    private javax.swing.JLabel txFechaNaci;
    private javax.swing.JLabel txNombre;
    private javax.swing.JLabel txTelefono;
    // End of variables declaration//GEN-END:variables
}
