/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package cap_presentacion;

import cap_logica.Cuenta;
import cap_logica.Estado;
import cap_logica.Strings;
import java.awt.Color;
import java.sql.Date;
import java.sql.ResultSet;
import javax.swing.JOptionPane;

/**
 *
 * @author Sh
 */
public class PnlPcsDepositar extends javax.swing.JPanel {
    
    private boolean encontrado = false;
    private boolean activa = true;

    /**
     * Creates new form PnlPcsDepositar
     */
    public PnlPcsDepositar() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        txTitulo = new javax.swing.JLabel();
        txNumCuenta = new javax.swing.JLabel();
        tfNumCuenta = new javax.swing.JTextField();
        btBuscar = new javax.swing.JButton();
        btLimpiar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        taInfo = new javax.swing.JTextArea();
        txMonto = new javax.swing.JLabel();
        tfMontoDeposito = new javax.swing.JTextField();
        btGuardar = new javax.swing.JButton();

        setBackground(new java.awt.Color(204, 204, 255));
        setLayout(new java.awt.GridBagLayout());

        txTitulo.setFont(new java.awt.Font("Tahoma", 0, 30)); // NOI18N
        txTitulo.setText("■ Depositar a una cuenta bancaria");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 4;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(20, 70, 0, 0);
        add(txTitulo, gridBagConstraints);

        txNumCuenta.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        txNumCuenta.setText("Número de Cuenta:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(30, 300, 0, 0);
        add(txNumCuenta, gridBagConstraints);

        tfNumCuenta.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        tfNumCuenta.setForeground(new java.awt.Color(153, 153, 153));
        tfNumCuenta.setText(Strings.ejmNumeroCuenta);
        tfNumCuenta.setCaretPosition(0);
        tfNumCuenta.setPreferredSize(new java.awt.Dimension(450, 35));
        tfNumCuenta.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                tfNumCuentaMousePressed(evt);
            }
        });
        tfNumCuenta.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tfNumCuentaKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tfNumCuentaKeyReleased(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(27, 20, 0, 0);
        add(tfNumCuenta, gridBagConstraints);

        btBuscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/buscarx32.png"))); // NOI18N
        btBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btBuscarActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(25, 30, 0, 0);
        add(btBuscar, gridBagConstraints);

        btLimpiar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/limpiarx32.png"))); // NOI18N
        btLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btLimpiarActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(25, 10, 0, 0);
        add(btLimpiar, gridBagConstraints);

        taInfo.setFont(new java.awt.Font("Monospaced", 0, 24)); // NOI18N
        taInfo.setEnabled(false);
        taInfo.setPreferredSize(new java.awt.Dimension(450, 37));
        jScrollPane1.setViewportView(taInfo);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 0.5;
        gridBagConstraints.weighty = 0.5;
        gridBagConstraints.insets = new java.awt.Insets(30, 200, 0, 200);
        add(jScrollPane1, gridBagConstraints);

        txMonto.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        txMonto.setText("Monto a depositar:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(30, 300, 0, 0);
        add(txMonto, gridBagConstraints);

        tfMontoDeposito.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        tfMontoDeposito.setForeground(new java.awt.Color(153, 153, 153));
        tfMontoDeposito.setText(Strings.ejmMonto);
        tfMontoDeposito.setPreferredSize(new java.awt.Dimension(450, 35));
        tfMontoDeposito.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                tfMontoDepositoMousePressed(evt);
            }
        });
        tfMontoDeposito.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tfMontoDepositoKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tfMontoDepositoKeyReleased(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(27, 20, 0, 0);
        add(tfMontoDeposito, gridBagConstraints);

        btGuardar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/savex48.png"))); // NOI18N
        btGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btGuardarActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.gridwidth = 4;
        gridBagConstraints.insets = new java.awt.Insets(30, 0, 20, 0);
        add(btGuardar, gridBagConstraints);
    }// </editor-fold>//GEN-END:initComponents

    private void btBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btBuscarActionPerformed
        // TODO add your handling code here:
        try{
            String numCuenta = tfNumCuenta.getText();
            Cuenta objCue = new Cuenta();

            ResultSet  resultado = objCue.buscarPorNumCuenta(numCuenta);

            while (resultado.next()){
                Date auxFechaApertura = resultado.getDate("fecha_apertura_cuenta");
                double auxMontoInicial = resultado.getDouble("monto_inicial_cuenta");
                String auxTipoMoneda = resultado.getString("tipo_moneda_cuenta");
                String auxTipoEstado = resultado.getString("estado_cuenta");
                String auxDniCliente = resultado.getString("dni_cliente_cuenta");

                taInfo.setText("DNI cliente: " + auxDniCliente +
                                "\nFecha apertura: " + auxFechaApertura.toString() +
                                "\nMonto: " + auxMontoInicial +
                                "\nTipo de moneda: " + auxTipoMoneda +
                                "\nEstado: " + auxTipoEstado);

                tfNumCuenta.setEnabled(false);
                encontrado = true;
                
                if(auxTipoEstado.equalsIgnoreCase(Estado.CERRADA.name())){
                    activa = false;
                }
            }

            if(!encontrado){
                taInfo.setText("Cuenta no encontrada");

                JOptionPane.showMessageDialog(this,"Numero de cuenta NO ENCONTRADA",
                    "MENSAJE DEL SISTEMA", JOptionPane.INFORMATION_MESSAGE);
            }
            
            if(!activa){
                JOptionPane.showMessageDialog(this,"Numero de cuenta CERRADA",
                    "MENSAJE DEL SISTEMA", JOptionPane.INFORMATION_MESSAGE);
            }
            
        }catch(Exception error){
            JOptionPane.showMessageDialog(this,error.getMessage(),
                "ERROR DEL SISTEMA", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btBuscarActionPerformed

    private void btLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btLimpiarActionPerformed
        // TODO add your handling code here:
        encontrado = false;
        activa = true;
        
        tfNumCuenta.setEnabled(true);
        
        tfNumCuenta.setText(Strings.ejmNumeroCuenta);
        tfNumCuenta.setCaretPosition(0);
        tfNumCuenta.setForeground(new Color(153,153,153));
        
        taInfo.setText("");
        taInfo.setCaretPosition(0);
        taInfo.setForeground(new Color(153,153,153));
        
        tfMontoDeposito.setText(Strings.ejmMonto);
        tfMontoDeposito.setCaretPosition(0);
        tfMontoDeposito.setForeground(new Color(153,153,153));
    }//GEN-LAST:event_btLimpiarActionPerformed

    private void btGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btGuardarActionPerformed
        // TODO add your handling code here:
        try {
            //'encontrado' tipo (boolean) para verificar si encontro a una cuenta ya existende en nuestra BD
            //'activa' tipo (boolean) para verificar si la cuenta se encuentra ACTIVA
            if(encontrado && activa){
                String cuenta = tfNumCuenta.getText();
                double deposito = Double.parseDouble(tfMontoDeposito.getText());
                Cuenta objCue = new Cuenta();

                objCue.depositarMonto(cuenta, deposito);

                JOptionPane.showMessageDialog(this,"Deposito aceptado",
                    "MENSAJE DEL SISTEMA", JOptionPane.INFORMATION_MESSAGE);

                encontrado = false;
                activa = true;
                
                tfNumCuenta.setEnabled(true);
                
                tfNumCuenta.setText(Strings.ejmNumeroCuenta);
                tfNumCuenta.setCaretPosition(0);
                tfNumCuenta.setForeground(new Color(153,153,153));
        
                taInfo.setText("");
                taInfo.setCaretPosition(0);
                taInfo.setForeground(new Color(153,153,153));
        
                tfMontoDeposito.setText(Strings.ejmMonto);
                tfMontoDeposito.setCaretPosition(0);
                tfMontoDeposito.setForeground(new Color(153,153,153));

            }else if(!encontrado){
                JOptionPane.showMessageDialog(this,"Primero debe buscar una cuenta",
                    "MENSAJE DEL SISTEMA", JOptionPane.ERROR_MESSAGE);
                
            }else if(!activa){
                JOptionPane.showMessageDialog(this,"Numero de cuenta CERRADA",
                    "MENSAJE DEL SISTEMA", JOptionPane.ERROR_MESSAGE);
            }
            
        } catch (Exception error) {
            JOptionPane.showMessageDialog(this,error.getMessage(),
                "ERROR DEL SISTEMA", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btGuardarActionPerformed

    /*
        DETALLES DE TEXT FIELD: 
            inicio del caret;
            color de letras. gris - ejemplo, rojo - incorrecto, negro - correcto;
            text field vacio = texto de ejemplo;
    */
    
    private void tfNumCuentaMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tfNumCuentaMousePressed
        // TODO add your handling code here:
        if(tfNumCuenta.getText().equals(Strings.ejmNumeroCuenta)){

            tfNumCuenta.setCaretPosition(0);
        }
    }//GEN-LAST:event_tfNumCuentaMousePressed

    private void tfNumCuentaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfNumCuentaKeyPressed
        // TODO add your handling code here:
        if(tfNumCuenta.getText().equals(Strings.ejmNumeroCuenta)){

            tfNumCuenta.setForeground(new Color(0,0,0));
            tfNumCuenta.setText("");
        }
    }//GEN-LAST:event_tfNumCuentaKeyPressed

    private void tfNumCuentaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfNumCuentaKeyReleased
        // TODO add your handling code here:
        boolean letra = false;
        
        if(tfNumCuenta.getCaretPosition() == 0 && tfNumCuenta.getText().equals("")){

            tfNumCuenta.setText(Strings.ejmNumeroCuenta);
            tfNumCuenta.setForeground(new Color(153,153,153));
            tfNumCuenta.setCaretPosition(0);
        }else{

            for (int i = 0; i < tfNumCuenta.getText().length(); i++) {
                char c = tfNumCuenta.getText().charAt(i);

                if(c != '1' && c != '2' && c != '3' && c != '4' && c != '5'
                    && c != '6' && c != '7' && c != '8' && c != '9' && c != '0'){

                    letra = true;
                }
            }
            
            if(letra == true || tfNumCuenta.getText().length() > 20){
                tfNumCuenta.setForeground(new Color(255,51,51)); // rojo
            }else{
                tfNumCuenta.setForeground(new Color(0,0,0)); // negro
            }
        }
    }//GEN-LAST:event_tfNumCuentaKeyReleased

    private void tfMontoDepositoMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tfMontoDepositoMousePressed
        // TODO add your handling code here:
        if(tfMontoDeposito.getText().equals(Strings.ejmMonto)){

            tfMontoDeposito.setCaretPosition(0);
        }
    }//GEN-LAST:event_tfMontoDepositoMousePressed

    private void tfMontoDepositoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfMontoDepositoKeyPressed
        // TODO add your handling code here:
        if(tfMontoDeposito.getText().equals(Strings.ejmMonto)){

            tfMontoDeposito.setForeground(new Color(0,0,0));
            tfMontoDeposito.setText("");
        }
    }//GEN-LAST:event_tfMontoDepositoKeyPressed

    private void tfMontoDepositoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfMontoDepositoKeyReleased
        // TODO add your handling code here:
        boolean letra = false;
        
        if(tfMontoDeposito.getCaretPosition() == 0 && tfMontoDeposito.getText().equals("")){

            tfMontoDeposito.setText(Strings.ejmMonto);
            tfMontoDeposito.setForeground(new Color(153,153,153));
            tfMontoDeposito.setCaretPosition(0);
        }else{

            for (int i = 0; i < tfMontoDeposito.getText().length(); i++) {
                char c = tfMontoDeposito.getText().charAt(i);

                if(c != '1' && c != '2' && c != '3' && c != '4' && c != '5'
                    && c != '6' && c != '7' && c != '8' && c != '9' && c != '0' && c != '.'){

                    letra = true;
                }
            }
            
            if(letra == true){
                tfMontoDeposito.setForeground(new Color(255,51,51)); // rojo
            }else{
                tfMontoDeposito.setForeground(new Color(0,0,0)); // negro
            }
        }
    }//GEN-LAST:event_tfMontoDepositoKeyReleased


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btBuscar;
    private javax.swing.JButton btGuardar;
    private javax.swing.JButton btLimpiar;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea taInfo;
    private javax.swing.JTextField tfMontoDeposito;
    private javax.swing.JTextField tfNumCuenta;
    private javax.swing.JLabel txMonto;
    private javax.swing.JLabel txNumCuenta;
    private javax.swing.JLabel txTitulo;
    // End of variables declaration//GEN-END:variables
}
