/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package cap_presentacion;

import cap_logica.Cuenta;
import cap_logica.Strings;
import java.awt.Color;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Sh
 */
public class PnlRptCuentasSegunCliente extends javax.swing.JPanel {

    /**
     * Creates new form PnlRptCuentasSegunCliente
     */
    public PnlRptCuentasSegunCliente() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        txTitulo = new javax.swing.JLabel();
        txDni = new javax.swing.JLabel();
        tfDni = new javax.swing.JTextField();
        btLista = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbLista = new javax.swing.JTable();

        setBackground(new java.awt.Color(204, 255, 204));
        setLayout(new java.awt.GridBagLayout());

        txTitulo.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        txTitulo.setText("> Listado de cuentas de un cliente especifico");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(30, 70, 0, 0);
        add(txTitulo, gridBagConstraints);

        txDni.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txDni.setText("DNI:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(20, 150, 0, 0);
        add(txDni, gridBagConstraints);

        tfDni.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        tfDni.setForeground(new java.awt.Color(153, 153, 153));
        tfDni.setText(Strings.ejmDni);
        tfDni.setCaretPosition(0);
        tfDni.setPreferredSize(new java.awt.Dimension(450, 28));
        tfDni.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                tfDniMousePressed(evt);
            }
        });
        tfDni.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tfDniKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tfDniKeyReleased(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.ipadx = 450;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(16, 18, 0, 0);
        add(tfDni, gridBagConstraints);

        btLista.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/refresh x32.png"))); // NOI18N
        btLista.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btListaActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(10, 100, 0, 0);
        add(btLista, gridBagConstraints);

        tbLista.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jScrollPane1.setViewportView(tbLista);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 0.5;
        gridBagConstraints.weighty = 0.5;
        gridBagConstraints.insets = new java.awt.Insets(20, 50, 50, 50);
        add(jScrollPane1, gridBagConstraints);
    }// </editor-fold>//GEN-END:initComponents

    private void btListaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btListaActionPerformed
        // TODO add your handling code here:
        try{
            String auxDni = tfDni.getText();
            DefaultTableModel modelo = new DefaultTableModel();
            Cuenta objC = new Cuenta();
            ResultSet  resultado = objC.listarCuentasSegunDni(auxDni);
            
            int nroColumnas = resultado.getMetaData().getColumnCount();
        
            for (int i=0; i<nroColumnas; i++){
                modelo.addColumn(resultado.getMetaData().getColumnLabel(i+1).toUpperCase());
            }
        
            Object datos[] = new Object[nroColumnas];
            
            while (resultado.next()){
                for(int i=0; i<nroColumnas;i++){
                    datos[i] = resultado.getObject(i+1);
                }
                
                modelo.addRow(datos);
            }
            tbLista.setModel(modelo);
            
            tfDni.setText(Strings.ejmDni);
            tfDni.setCaretPosition(0);
            tfDni.setForeground(new Color(153,153,153));
        }
        catch(Exception error)
        {
            JOptionPane.showMessageDialog(this,error.getMessage(),
                "ERROR DEL SISTEMA", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btListaActionPerformed

     /*
        DETALLES DE TEXT FIELD: 
            inicio del caret;
            color de letras. gris - ejemplo, rojo - incorrecto, negro - correcto;
            text field vacio = texto de ejemplo;
    */
    
    private void tfDniMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tfDniMousePressed
        // TODO add your handling code here:
        if(tfDni.getText().equals(Strings.ejmDni)){

            tfDni.setCaretPosition(0);
            //tfDni.setCaretColor(new Color(0,0,0));
        }
    }//GEN-LAST:event_tfDniMousePressed

    private void tfDniKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfDniKeyPressed
        // TODO add your handling code here:
        if(tfDni.getText().equals(Strings.ejmDni)){

            tfDni.setForeground(new Color(0,0,0));
            tfDni.setText("");
        }
    }//GEN-LAST:event_tfDniKeyPressed

    private void tfDniKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfDniKeyReleased
        // TODO add your handling code here:
        boolean letra = false;
        
        if(tfDni.getCaretPosition() == 0 && tfDni.getText().equals("")){

            tfDni.setText(Strings.ejmDni);
            tfDni.setForeground(new Color(153,153,153));
            tfDni.setCaretPosition(0);
        }else{

            for (int i = 0; i < tfDni.getText().length(); i++) {
                char c = tfDni.getText().charAt(i);

                if(c != '1' && c != '2' && c != '3' && c != '4' && c != '5'
                    && c != '6' && c != '7' && c != '8' && c != '9' && c != '0'){

                    letra = true;
                }
            }
            
            if(letra == true || tfDni.getText().length() > 8){
                tfDni.setForeground(new Color(255,51,51)); // rojo
            }else{
                tfDni.setForeground(new Color(0,0,0)); // negro
            }
        }
    }//GEN-LAST:event_tfDniKeyReleased


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btLista;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tbLista;
    private javax.swing.JTextField tfDni;
    private javax.swing.JLabel txDni;
    private javax.swing.JLabel txTitulo;
    // End of variables declaration//GEN-END:variables
}
